require 'sinatra/base'
require 'sinatra/json'
require 'thin'
require 'json'
require 'pry'
require 'httparty'
require 'yaml'

require_relative '../lib/transaction.rb'
require_relative '../lib/coinbase.rb'
require_relative '../lib/blockchain.rb'
require_relative '../wallet/wallet.rb'
require_relative '../lib/helpers.rb'
require_relative '../config.rb'
